name: MoBoosters
version: '${project.version}'
main: mv.mossuh.moboosters.MoBoosters
api-version: '1.13'

depend:
  - MoCore
  - NBTAPI

softdepend:
  - PlaceholderAPI
  - SuperiorSkyblock2
  - Vault
  - EssentialsX
  - JobsReborn
  - PlayerPoints

commands:
  moboosters:
    description: MoBoosters Commands
    aliases:
      - mobooster
      - moboost