name: MoBoosters
version: '${project.version}'
main: mv.mossuh.moboosters.MoBoosters
api-version: '1.13'

depend:
  - MoCore

softdepend:
  - NBTAPI
  - SuperiorSkyblock2
  - Vault

commands:
  moboosters:
    description: MoBoosters Commands
    aliases:
      - mobooster
      - moboost